import {
  calculateDemoHoldingCostBasis,
  calculateDemoHoldingMarketValue,
  calculateDemoHoldingTotalReturnPct,
} from '../calculations/demoPortfolioCalculations'
import { KpiCard } from '../components/common/KpiCard'
import type { Holding, PortfolioSummary } from '../types'

const currencyFormat = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })
const percentFormat = new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 })

interface PortfolioViewProps {
  holdings: Holding[]
  includedTickers: Set<string>
  summary: PortfolioSummary
  onToggleHolding: (ticker: string) => void
  onOpenPosition: (ticker: string) => void
}

export const PortfolioView = ({
  holdings,
  includedTickers,
  summary,
  onToggleHolding,
  onOpenPosition,
}: PortfolioViewProps) => {
  return (
    <section className="view-stack">
      <p className="view-note">
        Synthetic demo data. Portfolio totals are generated by the <code>demoPortfolioCalculations</code> placeholder
        layer.
      </p>

      <section className="kpi-grid">
        <KpiCard label="Portfolio Value" value={currencyFormat.format(summary.portfolioValue)} />
        <KpiCard label="Cost Basis" value={currencyFormat.format(summary.costBasis)} tone="muted" />
        <KpiCard
          label="Total Profit"
          value={currencyFormat.format(summary.totalProfit)}
          tone={summary.totalProfit >= 0 ? 'positive' : 'negative'}
        />
        <KpiCard
          label="Total Return"
          value={`${percentFormat.format(summary.totalReturnPct)}%`}
          tone={summary.totalReturnPct >= 0 ? 'positive' : 'negative'}
        />
        <KpiCard
          label="Annualized Return / XIRR"
          value={`${percentFormat.format(summary.annualizedReturnPlaceholderPct)}%`}
          tone="muted"
        />
        <KpiCard
          label="Dividend Income"
          value={currencyFormat.format(summary.dividendIncomePlaceholder)}
          tone="default"
        />
      </section>

      <section className="panel">
        <div className="panel-title-row">
          <h2>Holdings</h2>
          <p>Toggle inclusion to update demo aggregation and portfolio weights.</p>
        </div>

        <div className="table-scroll">
          <table>
            <thead>
              <tr>
                <th>Include</th>
                <th>Ticker</th>
                <th>Name</th>
                <th>Cost Basis</th>
                <th>Market Value</th>
                <th>Total Return</th>
                <th>Weight</th>
              </tr>
            </thead>
            <tbody>
              {holdings.map((holding) => {
                const isIncluded = includedTickers.has(holding.ticker)
                const weight = summary.weightsByTicker[holding.ticker] ?? 0
                const totalReturn = calculateDemoHoldingTotalReturnPct(holding)
                return (
                  <tr key={holding.ticker} className={isIncluded ? '' : 'excluded'}>
                    <td>
                      <label className="toggle-cell">
                        <input
                          type="checkbox"
                          checked={isIncluded}
                          onChange={() => onToggleHolding(holding.ticker)}
                        />
                        <span>{isIncluded ? 'ON' : 'OFF'}</span>
                      </label>
                    </td>
                    <td>
                      <button type="button" className="linkish" onClick={() => onOpenPosition(holding.ticker)}>
                        {holding.ticker}
                      </button>
                    </td>
                    <td>{holding.name}</td>
                    <td>{currencyFormat.format(calculateDemoHoldingCostBasis(holding))}</td>
                    <td>{currencyFormat.format(calculateDemoHoldingMarketValue(holding))}</td>
                    <td className={totalReturn >= 0 ? 'positive' : 'negative'}>{percentFormat.format(totalReturn)}%</td>
                    <td>{percentFormat.format(weight)}%</td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </section>
    </section>
  )
}
